import axios from 'axios'
import Head from 'next/head'
import App from "../src/App"

const Home = ({yosemiteWeather}: any) => {
  console.log(yosemiteWeather);
  return (
    <>
      <Head>
        <title>Erick Bravo Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App yosemiteWeather={yosemiteWeather} />
    </>
  )
}

export default Home;

export const getServerSideProps = async () => {
  const nonDynamicURL = `https://api.openweathermap.org/data/2.5/weather?lat=${37.7456}&lon=${-119.5936}&units=imperial&appid=${
    process.env.NEXT_PUBLIC_WEATHER_KEY
  }`;

  try {
    const yosemiteWeather = await axios.get(nonDynamicURL);

    return {
      props: {
        yosemiteWeather: yosemiteWeather.data,
      },
    };
  } catch (error: any) {
    console.error(error.response);
  }
};